/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/bag.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bag.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 2.235, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={392.58}>
        <mesh geometry={nodes.PunchingBag1_1.geometry} material={materials.Bag1PunchingBag1} />
        <mesh geometry={nodes.PunchingBag1_2.geometry} material={materials.Base1PunchingBag1} />
        <mesh geometry={nodes.PunchingBag1_3.geometry} material={materials.Bar1PunchingBag1} />
      </group>
    </group>
  )
}

useGLTF.preload('/bag.glb')
